receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlp/data-prepper-traces:
    endpoint: data-prepper:21890
    tls:
      insecure: true
  otlp/data-prepper-metrics:
    endpoint: data-prepper:21891
    tls:
      insecure: true
  otlp/data-prepper-logs:
    endpoint: data-prepper:21892
    tls:
      insecure: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/data-prepper-traces]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/data-prepper-metrics]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/data-prepper-logs]
